name: Deploy fms_communication to prod
on:
  push:
    branches: [ leap ]
    paths: 'services/fms_communication/**'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{secrets.DEFAULT_WORKING_DIRECTORY}}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2     

      # Runs a set of commands using the runners shell
      - name: Change directory to FMS
        run: |
          cd ${{secrets.DEFAULT_WORKING_DIRECTORY}}
          
      - name: git pull       
        run: |
          git pull

      - name: build communication container
        run: docker-compose up --no-deps --build -d communication
