name: Deploy Feed to stage
on:
  push:
    branches: [ leap-beta ]

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            images:
              - 'images/**'
            misc:
              - 'misc/**'
      - print:
        run: |
          echo ${{steps.changes.outputs}}

          