name: Deploy Feed to stage
on:
  push:
    branches: [ leap-beta ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /Users/arshavir/Documents/gh

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: git pull
        run: |
          echo pwd
          echo $GITHUB_WORKSPACE
