name: Deploy Feed to stage
on:
  push:
    branches: [ leap-beta ]
    paths: 'services/fms_feed/**'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ~/Documents/work/FMS

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Change directory to FMS
        run: |
          cd ~/Documents/work/FMS/fms_toolkit
      - name: git pull
        run: |
          git pull
      - name: build feed-next container
        env:
          fms_env: staging
        run: docker-compose up --no-deps --build -d feed-next