name: Deploy Feed to stage
on:
  push:
    branches: [ leap-beta ]
    paths: 'images/**'

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT